# Generated by Django 4.1.5 on 2023-03-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='matn',
            field=models.TextField(),
        ),
    ]
